### ISSUE TITLE
Build error!

### ISSUE THREAD

**Issue by anindex** [aecins/symseg#1]
Hi, I am very interested in your research. However, I met the following issue about Octomap linking error  when compiling your repos. 
`Linking CXX executable ../../../bin/full_segmentation
Linking CXX executable ../../../bin/reflectional_segmentation
Linking CXX executable ../../../bin/rotational_segmentation
CMakeFiles/full_segmentation.dir/main.cpp.o: In function `octomap::OccupancyOcTreeBase<octomap::OcTreeNode>::readBinaryNode(std::istream&, octomap::OcTreeNode*) const':
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x9e): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x11c): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x21d): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x249): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x282): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
CMakeFiles/full_segmentation.dir/main.cpp.o:main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x2ce): more undefined references to `octomap::OcTreeNode::createChild(unsigned int)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/full_segmentation] Error 1
make[1]: *** [examples/full_segmentation/CMakeFiles/full_segmentation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/reflectional_segmentation.dir/main.cpp.o: In function `octomap::OccupancyOcTreeBase<octomap::OcTreeNode>::readBinaryNode(std::istream&, octomap::OcTreeNode*) const':
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x9e): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x11c): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x21d): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x249): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x282): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
CMakeFiles/reflectional_segmentation.dir/main.cpp.o:main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x2ce): more undefined references to `octomap::OcTreeNode::createChild(unsigned int)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/reflectional_segmentation] Error 1
make[1]: *** [examples/reflectional_segmentation/CMakeFiles/reflectional_segmentation.dir/all] Error 2
CMakeFiles/rotational_segmentation.dir/main.cpp.o: In function `octomap::OccupancyOcTreeBase<octomap::OcTreeNode>::readBinaryNode(std::istream&, octomap::OcTreeNode*) const':
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x9e): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x11c): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x21d): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x249): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x282): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
CMakeFiles/rotational_segmentation.dir/main.cpp.o:main.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x2ce): more undefined references to `octomap::OcTreeNode::createChild(unsigned int)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/rotational_segmentation] Error 1
make[1]: *** [examples/rotational_segmentation/CMakeFiles/rotational_segmentation.dir/all] Error 2
make: *** [all] Error 2
`
I am sure that I have installed correctly PCL 1.8 and Octomap 1.8.1 on Ubuntu 14.04.
Thanks in advance!

**Comment by aecins** [comment]
It looks like the code can't link to OctoMap library properly. It can find the header files with function definitions, but not the .so files. Here are the things to check:
1) Did you `sudo make install` OctoMap on your computer after building it?
2) Do you have ROS installed on your machine? ROS has it's own version of OctoMap, that might conflict with a fresh install of OctoMap 1.8.1.

**Comment by anindex** [comment]
Hi, I have checked the conditions you provided and it seem that ROS Indigo Octomap conflicts with Octomap 1.8. I think the cmake included directory "/usr/local/lib" that cover also "/usr/local/indigo/lib" hence the conflict happened.
I removed the ROS Octomap (1.6) and it resolves my problem.
Thank you very much :)

**Comment by aecins** [comment]
Great, glad it worked out!
